# Generated by Django 2.2 on 2020-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discountprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
