# Generated by Django 2.2 on 2020-02-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discountprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discountprice',
            new_name='discount_price',
        ),
    ]
