# Generated by Django 2.2 on 2020-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200226_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=' this is a text description '),
            preserve_default=False,
        ),
    ]
